name: Build FARALAG AC GUI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build GUI
        shell: cmd
        run: |
          cl /nologo /std:c++17 /EHsc /O2 /DUNICODE /D_UNICODE FARALAG_AC.cpp /link /SUBSYSTEM:WINDOWS winhttp.lib comctl32.lib /OUT:FARALAG_AC.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: FARALAG_AC_GUI_V1
          path: FARALAG_AC.exe
